server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Tüm istekleri index.html'e yönlendir — React Router halleder
    location / {
        try_files $uri $uri/ /index.html;
    }
}
